# calculator using operator
#first=int(input("enter first number is"))
# operator=(input("enter operator (+,-,*,/,%,//) :"))
# second=int(input("enter second number is:"))

# if operator == "+":
#     print(first+second)
# elif operator == "-":
#     print(first-second)
# elif operator == "*":
#     print(first*second)
# elif operator == "/":
#     print(first/second)
# elif operator == "//":
#     print(first//second)
# else:
#     print("invalid operation")

#patern check karva mate
# i=1
# while i<=5:
#     print(i *  " *")
#     i=i+1

#reverse pattern
# i=4
# while i>=0:
#     print(i * " *")
#     i=i-1

# aa case ma 1 to 10 num print thse
# for i in range(10):
#     print(i+1)

#marks print thse
# marks=[95,92,97,58]
# print(marks)

# # append use thse list last num add karva
# marks=[95,92,97,58]
# (marks.append(20))
# print(marks)

# #insert use thse list ma start,middle and last num add karva mate
# marks=[75,82,54,63,24]
# marks.insert(0,50)
# print(marks)

# # for i in marks:
# #     print(i)


# #aa check karse 85 ae marks che k nahi(in operator use karine)
# marks=[95,92,97,58]
# print(85 in marks)

# #len ae list check karse it means count karse (1,2,3,etc)
# marks=[95,92,97,58,10]
# print(len(marks))

# #use while loop print thse (one by one num)
# marks=[41,78,54,23,13]

# i=0
# while i< len(marks):
#     print(marks[i])
#     i=i+1

# # clear ae aakhi list clear kari dese
# list=[81,82,83]
# list.clear()
# print(list)

# # break use loop break karva suppose dev pachina name list aakhu break thse
# students=["ram","shyam","kishan","dev","madhu","remli"]

# for student in students:
#     if student=="dev":
#         break;
#     print(student)

#     students=["ram","shyam","kishan","dev","madhu","remli"]

# # countinue use thse list mathi name remove karva
# for student in students:
#     if student=="kishan":
#         continue;
#     print(student)

# # tuple ma aapde list change na kari sakiye

# number=(25,54,96,54,54)
# print(number.count(54))
# print(number.index(96))

# # set represent karse {} means 45 value 1 var print kare
# value={32,45,45,30}
# print(value)

# for score  in value:
#     print(score)

# # use distonary

# marks={"chemastry":84,"maths":89}

# marks["physics"] =97
# print(marks)

# marks["chemastry"]=68
# print(marks)

# import math

# print("tapovan")
# print(math.gcd(3,6))

# a=48
# b="meet"

# value=type(a)
# print(type)

# val=type(b)
# print(type)




# i=1
# while i<=100:
#     print()
#     i=i+1



a=8
b=7
print(a+b)


    




  