#def cube(number):
    #return number*number*number

#def by_three(num):
    #if(num%3==0):
        #res=cube(num)
        #return res
    #else:
        #return False
#i=int(input("Enter the number which is divisible by three: "))
#s=by_three(i)
#print("The ans is: ",s)
    
#(def prime(start,end):
    #for i in range(start,end+1):
        #flag=0
        #for j in range(2,i):
           # if(i%j==0):
             #   flag=1
        ##if(flag==0):
           # print("Prime number is :",i)
#ic=int(input("Enter the starting point is: "))
#id=int(input("Enter the ending point is:")) 
#print(prime(ic,id)))

# def sum(n1,n2):
#     return n1+n2
# def sub(n1,n2):
#     return n1-n2
# def mul(n1,n2):
#     return n1*n2
# def div(n1,n2):
#     return n1/n2

# def cal(operation,n1,n2):
#     match operation:
#         case 0:
#             s=sum(n1,n2)
#             return s
#         case 1:
#             s=sub(n1,n2)
#             return s
#         case 2:
#             d=mul(n1,n2)
#             return d
#         case 3:
#             m=div(n1,n2)
#             return m
#         case default:
#             s="wrong number added"
#             return s
        
# n1=int(input("Enter the number 1 :"))
# n2=int(input("Enter the number 2 :"))
# n3=int(input("Enter the operation number o for sum,1 for sub,2 for mul,3 for division:"))
# Ans=cal(n3,n2,n1)
# print("The Ans is:",Ans)


# def cube(number):
#     return number*number*number

# def by_three(num):
#     if num%3==0:
#         res=cube(num)
#         return res
#     else:
#         return False
    
# i=int(input("enter num"))
# s=by_three(i)
# print("ans is",s)

# def prime(start,end):

#     for i in range(start,end+1):
#         flag=0

#         for j in range(2,i):
#             if i%j==0:
#                 flag=1
#         if(flag==0):
#             print("Prime num",i)

# ic=int(input("start num"))
# id=int(input("end num"))

# print(prime(ic,id))

# def fact(number):

#     c=1
#     for i in range(1,number+1):
#         c=c*i
#     return c
    
# y=int(input("Eter num"))
# f=fact(y)
# print("ans is",f)


students= {"student":1 ,"Rollno":1, "name":"Meet","semester":2,"course":"Mba","percentage":45}
{"student":2,"Rollno":1, "name":"Meet","semester":5,"course":"Mba","percentage":45},
{"student":3 ,"Rollno":1, "name":"Meet","semester":6,"course":"Mba","percentage":45}
# {"Rollno":1, "name":"Meet","semester":2,"course":"Mba","percentage":45},
# {"Rollno":1, "name":"Meet","semester":2,"course":"Mba","percentage":45}


students["student":3]["Semester"]=2
